# Generated by Django 4.2.11 on 2024-03-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(help_text='公众号id', primary_key=True, serialize=False)),
                ('fake_id', models.CharField(help_text='公众号唯一标识，系统给定', max_length=32)),
                ('name', models.CharField(help_text='公众号名称', max_length=32)),
                ('create_time', models.DateField(help_text='在系统添加时间')),
            ],
            options={
                'verbose_name': 'account',
            },
        ),
        migrations.CreateModel(
            name='MyAccount',
            fields=[
                ('id', models.AutoField(help_text='公众号id', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='公众号名称', max_length=32)),
                ('cookie', models.CharField(help_text='公众号名称', max_length=32)),
                ('token', models.CharField(help_text='公众号token', max_length=32)),
                ('isactivate', models.IntegerField(default=0, help_text='是否作为当前爬取公号,0 不激活 1激活， 默认0')),
            ],
            options={
                'verbose_name': 'my_account',
            },
        ),
    ]
