# Generated by Django 4.2.11 on 2024-03-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='cookie',
            field=models.TextField(help_text='公众号cookie'),
        ),
    ]
