# Generated by Django 4.2.11 on 2024-03-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myaccount_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_time',
            field=models.DateField(auto_now=True, help_text='在系统添加时间'),
        ),
    ]
