# Generated by Django 4.2.11 on 2024-03-26 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(help_text='任务id', primary_key=True, serialize=False)),
                ('start_time', models.DateField(help_text='任务开始时间')),
                ('end_time', models.DateField(help_text='任务结束时间')),
                ('keyword', models.CharField(default='', help_text='查询关键字', max_length=32)),
                ('status', models.IntegerField(help_text='任务状态0 待运行 1运行中 2 运行完成')),
                ('pagenum', models.IntegerField(help_text='上次运行页码')),
                ('timegap', models.IntegerField(help_text='下载间隔时间')),
                ('link_cnt', models.IntegerField(help_text='上次记录的文章链接数')),
                ('down_cnt', models.IntegerField(help_text='上次下载的文章数')),
                ('total', models.IntegerField(help_text='上次的文章总数')),
                ('create_time', models.DateField(help_text='任务创建时间')),
                ('update_time', models.DateField(help_text='任务修改时间')),
                ('pid', models.ForeignKey(help_text='公众号id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
            ],
            options={
                'verbose_name': 'task_status',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aid', models.CharField(help_text='文章id,具有唯一标识', max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='文章标题', max_length=128)),
                ('link', models.CharField(help_text='文章链接', max_length=256)),
                ('cover', models.CharField(help_text='封面链接', max_length=256)),
                ('status', models.IntegerField(default=0, help_text='状态 0 未下载 1下载完成')),
                ('create_time', models.DateField(help_text='记录创建时间')),
                ('update_time', models.DateField(help_text='记录更新时间')),
                ('pid', models.ForeignKey(help_text='公众号id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
            ],
            options={
                'verbose_name': 'article',
            },
        ),
    ]
